name: imot
description: Inter Express Mobile Operation Transport - Mobile
publish_to: 'none' 
version: 1.0.0+1

environment:
  #sdk: '>=3.0.0 <4.0.0'
  sdk: '>=2.18.1 < 3.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 

  cupertino_icons: ^1.0.5
  get: ^4.6.5
  logger: ^1.1.0
  jwt_decoder: ^2.0.1
  package_info_plus: ^3.0.2
  uuid: ^3.0.7
  intl: ^0.17.0
  device_apps: ^2.2.0
  flutter_svg: ^1.1.6
  battery_plus: ^3.0.2
  dropdown_search: ^5.0.5
  dio: ^4.0.6
  cron: ^0.5.1
  flutter_background_service: ^2.4.6
  flutter_dotenv: ^5.0.2
  share_plus: ^6.3.0
  google_maps_flutter: ^2.2.2
  flutter_polyline_points: ^1.0.0
  permission_handler: ^10.2.0
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  flutter_screenutil: ^5.6.0
  flutter_keyboard_visibility: ^5.4.0
  flutter_rounded_date_picker: ^3.0.2
  image_picker: ^0.8.6+1
  flutter_easyloading: ^3.0.5
  qr_code_scanner: ^1.0.1
  google_fonts: ^3.0.1
  barcode: ^2.2.3
  signature: ^5.3.0
  firebase_core: ^2.4.0
  firebase_messaging: ^14.2.1
  firebase_remote_config: ^3.0.7
  dropdown_plus: ^0.0.9
  url_launcher: ^6.1.7
  get_storage: ^2.0.3
  flutter_multi_formatter: ^2.9.11
  awesome_notifications_fcm: ^0.7.4+1
  awesome_notifications: ^0.7.4+1
  connectivity_plus: ^3.0.2
  group_button: ^5.2.2
  badges: ^3.0.2
  flutter_image_compress: ^1.1.3
  just_audio: ^0.9.30
  flutter_email_sender: ^5.2.0
  web_socket_channel: ^2.2.0
  drift: ^2.5.0
  sqlite3_flutter_libs: ^0.5.12
  reorderables: ^0.5.1
  path_provider: ^2.0.11
  path: ^1.8.2
  undo: ^1.4.0
  upgrader: ^5.0.0
  # flutter_native_splash: ^2.2.15
  disk_space: ^0.2.1
  percent_indicator: ^4.2.2
  fl_chart: ^0.55.2
  easy_app_installer: ^1.0.0
  shared_preferences: ^2.1.2
  # mobile_scanner:
  #   git:
  #     url: https://github.com/juliansteenbakker/mobile_scanner.git
  #     ref: feature/scan-window
  google_huawei_availability: ^1.4.0
  wakelock: ^0.6.2
  location: ^4.4.0
  device_information: ^0.0.4
  restart_app: ^1.1.1+1
  device_info_plus: ^8.0.0
  system_info_plus: ^0.0.5
  system_info2: ^2.0.4
  flutter_cache_manager: ^3.3.0
  image: ^3.2.2
  slider_button: ^2.0.0
  mobile_scanner: ^2.1.0
  colorfilter_generator: ^0.0.8
  flutter_countdown_timer: ^4.1.0
  flutter_native_image: ^0.0.6
  camera_camera: ^3.0.0-dev
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: '^0.11.0'
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  drift_dev: ^2.8.3
  flex_color_scheme: ^6.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/config/
    - assets/images/
    - assets/sound/
    - assets/fonts/
    
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf